import type { FormSchema } from "@/lib/calculations/schemas";

const powerUnits = [
  { value: "kW", label: "kW" },
  { value: "W", label: "W" },
  { value: "HP", label: "HP" },
];
const voltageUnits = [
  { value: "V", label: "V" },
  { value: "kV", label: "kV" },
];
const lengthUnits = [
  { value: "m", label: "m" },
  { value: "km", label: "km" },
];
const phaseOpts = [
  { value: "3", label: "3상" },
  { value: "1", label: "단상" },
];
const cuAl = [
  { value: "cu", label: "구리" },
  { value: "al", label: "알루미늄" },
];

export const extraFormSchemas: Record<string, FormSchema> = {
  "motor-current": {
    slug: "motor-current",
    layout: "complex",
    defaults: { phase: "3", power: "30", powerUnit: "kW", voltage: "380", voltageUnit: "V", pf: "0.85", efficiency: "0.92" },
    fields: [
      { id: "phase", label: "회로", kind: "select", options: phaseOpts },
      { id: "power", label: "모터 출력", kind: "number", required: true, min: 0, step: "any", unitField: "powerUnit", units: powerUnits, hint: "축출력. 예: 380V 3상 30kW" },
      { id: "voltage", label: "전압", kind: "number", required: true, min: 0, step: "any", unitField: "voltageUnit", units: voltageUnits },
      { id: "pf", label: "역률 PF", kind: "number", min: 0, max: 1, step: "0.01" },
      { id: "efficiency", label: "효율 η", kind: "number", min: 0, max: 1, step: "0.01" },
    ],
  },
  "motor-starting": {
    slug: "motor-starting",
    layout: "complex",
    defaults: {
      flcMode: "known",
      phase: "3",
      power: "30",
      powerUnit: "kW",
      voltage: "380",
      voltageUnit: "V",
      pf: "0.85",
      efficiency: "0.92",
      flc: "60",
      method: "dol",
      multiplier: "",
      length: "",
      resistance: "",
      allowPct: "",
    },
    fields: [
      {
        id: "flcMode",
        label: "정격전류 입력",
        kind: "select",
        section: "1단계 · 모터 정보",
        options: [
          { value: "known", label: "정격전류를 알고 있음" },
          { value: "from-nameplate", label: "출력·전압으로 정격전류 계산" },
        ],
      },
      {
        id: "phase",
        label: "상수",
        kind: "select",
        section: "1단계 · 모터 정보",
        options: phaseOpts,
      },
      {
        id: "power",
        label: "정격 출력",
        kind: "number",
        min: 0,
        step: "any",
        unitField: "powerUnit",
        units: powerUnits,
        section: "1단계 · 모터 정보",
        visibleWhen: { field: "flcMode", values: ["from-nameplate"] },
        hint: "축출력. 예: 380 V 3상 30 kW",
      },
      {
        id: "voltage",
        label: "정격 전압",
        kind: "number",
        min: 0,
        step: "any",
        unitField: "voltageUnit",
        units: voltageUnits,
        section: "1단계 · 모터 정보",
        hint: "기동 전압강하 %의 분모로도 씁니다. 3상은 선간전압.",
      },
      {
        id: "pf",
        label: "역률 PF",
        kind: "number",
        min: 0,
        max: 1,
        step: "0.01",
        section: "1단계 · 모터 정보",
        visibleWhen: { field: "flcMode", values: ["from-nameplate"] },
      },
      {
        id: "efficiency",
        label: "효율 η",
        kind: "number",
        min: 0,
        max: 1,
        step: "0.01",
        section: "1단계 · 모터 정보",
        visibleWhen: { field: "flcMode", values: ["from-nameplate"] },
      },
      {
        id: "flc",
        label: "정격전류 FLC A",
        kind: "number",
        min: 0,
        step: "any",
        section: "1단계 · 모터 정보",
        visibleWhen: { field: "flcMode", values: ["known"] },
      },
      {
        id: "method",
        label: "기동방식",
        kind: "select",
        section: "2단계 · 기동 조건",
        options: [
          { value: "dol", label: "DOL 직입" },
          { value: "star-delta", label: "Y-Δ" },
          { value: "soft", label: "소프트스타터" },
          { value: "vfd", label: "VFD" },
        ],
        hint: "방식별 숫자는 참고값입니다. 표준 기본값으로 단정하지 않습니다.",
      },
      {
        id: "multiplier",
        label: "기동배수 (비우면 방식별 참고값)",
        kind: "number",
        min: 0,
        step: "any",
        section: "2단계 · 기동 조건",
        hint: "명판 구속전류 또는 컨트롤러 설정값을 우선하세요. 비우면 방식별 참고값을 씁니다.",
      },
      {
        id: "length",
        label: "편도 길이 m (선택)",
        kind: "number",
        min: 0,
        step: "any",
        section: "4단계 · 기동 전압강하",
        hint: "길이·저항·전압을 넣으면 기존 저항 근사로 기동 시 전압강하를 계산합니다.",
      },
      {
        id: "resistance",
        label: "도체 저항 Ω/km (선택)",
        kind: "number",
        min: 0,
        step: "any",
        section: "4단계 · 기동 전압강하",
      },
      {
        id: "allowPct",
        label: "사용자 허용 전압강하 % (선택)",
        kind: "number",
        min: 0,
        step: "any",
        section: "4단계 · 기동 전압강하",
        hint: "프로젝트 허용치입니다. 규정 합격 판정이 아닙니다.",
      },
    ],
  },
  "motor-start-vd": {
    slug: "motor-start-vd",
    layout: "complex",
    defaults: { phase: "3", flc: "60", multiplier: "6", length: "80", resistance: "0.524", voltage: "380", voltageUnit: "V", allowPct: "15" },
    fields: [
      { id: "phase", label: "회로", kind: "select", options: phaseOpts },
      { id: "flc", label: "FLC A", kind: "number", required: true, min: 0, step: "any" },
      { id: "multiplier", label: "기동배수", kind: "number", required: true, min: 0, step: "any" },
      { id: "length", label: "편도 길이 m", kind: "number", required: true, min: 0, step: "any" },
      { id: "resistance", label: "도체 저항 Ω/km", kind: "number", required: true, min: 0, step: "any" },
      { id: "voltage", label: "전압", kind: "number", required: true, min: 0, step: "any", unitField: "voltageUnit", units: voltageUnits },
      { id: "allowPct", label: "사용자 허용 전압강하 %", kind: "number", min: 0, step: "any" },
    ],
  },
  "motor-acceleration": {
    slug: "motor-acceleration",
    layout: "complex",
    defaults: { inertia: "2.5", rpm: "1450", torque: "80" },
    fields: [
      { id: "inertia", label: "등가 관성 J kg·m²", kind: "number", required: true, min: 0, step: "any", hint: "모터+부하 환산 관성" },
      { id: "rpm", label: "정격 회전수 r/min", kind: "number", required: true, min: 0, step: "any" },
      { id: "torque", label: "평균 가속 토크 N·m", kind: "number", required: true, min: 0, step: "any" },
    ],
  },
  "power-factor-correction": {
    slug: "power-factor-correction",
    layout: "complex",
    defaults: { powerKw: "320", pfNow: "0.78", pfTarget: "0.95", phase: "3", voltage: "380", voltageUnit: "V" },
    fields: [
      { id: "powerKw", label: "유효전력 kW", kind: "number", required: true, min: 0, step: "any" },
      { id: "pfNow", label: "현재 역률", kind: "number", required: true, min: 0, max: 1, step: "0.01" },
      { id: "pfTarget", label: "목표 역률", kind: "number", required: true, min: 0, max: 1, step: "0.01" },
      { id: "phase", label: "회로", kind: "select", options: phaseOpts },
      { id: "voltage", label: "전압 (전류 감소량 계산용)", kind: "number", min: 0, step: "any", unitField: "voltageUnit", units: voltageUnits },
    ],
  },
  "power-triangle": {
    slug: "power-triangle",
    layout: "complex",
    defaults: { mode: "ps", kw: "80", kva: "100", kvar: "60", pf: "0.8" },
    fields: [
      {
        id: "mode",
        label: "입력",
        kind: "select",
        options: [
          { value: "ps", label: "P와 S" },
          { value: "pq", label: "P와 Q" },
          { value: "ppf", label: "P와 PF" },
        ],
      },
      { id: "kw", label: "유효전력 kW", kind: "number", required: true, min: 0, step: "any" },
      { id: "kva", label: "피상전력 kVA", kind: "number", min: 0, step: "any", visibleWhen: { field: "mode", values: ["ps"] } },
      { id: "kvar", label: "무효전력 kvar", kind: "number", step: "any", visibleWhen: { field: "mode", values: ["pq"] } },
      { id: "pf", label: "역률", kind: "number", min: 0, max: 1, step: "0.01", visibleWhen: { field: "mode", values: ["ppf"] } },
    ],
  },
  thd: {
    slug: "thd",
    layout: "complex",
    defaults: { kind: "voltage", fundamental: "220", harmonics: "8, 4, 2" },
    fields: [
      { id: "kind", label: "구분", kind: "select", options: [{ value: "voltage", label: "전압 THD" }, { value: "current", label: "전류 THD" }] },
      { id: "fundamental", label: "기본파 실효값", kind: "number", required: true, min: 0, step: "any" },
      { id: "harmonics", label: "고조파 실효값 (쉼표 구분)", kind: "textarea", required: true, placeholder: "예: 8, 4, 2", hint: "H2, H3, … 순서 무관. 기본파는 넣지 마세요." },
    ],
  },
  "harmonic-filter": {
    slug: "harmonic-filter",
    layout: "complex",
    defaults: { qc: "100", voltage: "380", voltageUnit: "V", reactorPct: "7" },
    fields: [
      { id: "qc", label: "콘덴서 용량 kvar", kind: "number", required: true, min: 0, step: "any" },
      { id: "voltage", label: "선간전압", kind: "number", required: true, min: 0, step: "any", unitField: "voltageUnit", units: voltageUnits },
      { id: "reactorPct", label: "직렬 리액터 %", kind: "number", min: 0, step: "any", hint: "7%는 5고조파 디튠에 자주 쓰이는 예. 현장 확정값이 아님" },
    ],
  },
  "cable-sizing": {
    slug: "cable-sizing",
    layout: "complex",
    defaults: {
      mode: "basic",
      phase: "3",
      power: "45",
      powerUnit: "kW",
      voltage: "380",
      voltageUnit: "V",
      pf: "0.85",
      efficiency: "1",
      demand: "1",
      length: "80",
      lengthUnit: "m",
      allowPct: "3",
      material: "cu",
      insulation: "unspecified",
      parallel: "1",
      kTemp: "1",
      kGroup: "1",
      kInstall: "1",
      selectedMm2: "35",
      izTable: "",
      install: "unspecified",
      ambient: "30",
      grouping: "",
      burialM: "",
      soil: "unspecified",
      iscKa: "",
      tsc: "1",
      kAdiabatic: "",
    },
    fields: [
      { id: "mode", label: "계산 모드", kind: "select", options: [{ value: "basic", label: "기본 계산" }, { value: "detailed", label: "상세 계산" }] },
      { id: "phase", label: "회로", kind: "select", options: phaseOpts },
      { id: "power", label: "부하전력", kind: "number", required: true, min: 0, step: "any", unitField: "powerUnit", units: powerUnits },
      { id: "voltage", label: "전압", kind: "number", required: true, min: 0, step: "any", unitField: "voltageUnit", units: voltageUnits },
      { id: "pf", label: "역률", kind: "number", min: 0, max: 1, step: "0.01" },
      { id: "length", label: "거리", kind: "number", required: true, min: 0, step: "any", unitField: "lengthUnit", units: lengthUnits },
      { id: "allowPct", label: "허용 전압강하 %", kind: "number", required: true, min: 0, step: "any" },
      { id: "material", label: "도체 Cu / Al", kind: "select", options: cuAl, advanced: true },
      { id: "insulation", label: "절연 종류 (기록)", kind: "select", advanced: true, options: [
        { value: "unspecified", label: "미지정" },
        { value: "pvc", label: "PVC" },
        { value: "xlpe", label: "XLPE" },
        { value: "epr", label: "EPR" },
      ], hint: "허용전류를 자동 적용하지 않습니다. 표 조회용 기록입니다." },
      { id: "install", label: "포설방식 (기록)", kind: "select", advanced: true, options: [
        { value: "unspecified", label: "미지정" },
        { value: "tray", label: "트레이" },
        { value: "conduit", label: "관로" },
        { value: "buried", label: "지중" },
        { value: "air", label: "공중/내벽" },
      ], hint: "보정계수는 아래 k에 표 값을 직접 넣으세요." },
      { id: "ambient", label: "주변온도 °C (기록)", kind: "number", step: "any", advanced: true },
      { id: "grouping", label: "집합 회선 수 (기록)", kind: "number", min: 0, step: "1", advanced: true, hint: "집합 보정 k는 표에서 읽어 아래 칸에 넣습니다." },
      { id: "parallel", label: "병렬 회선 수", kind: "number", min: 1, step: "1", advanced: true },
      { id: "burialM", label: "매설깊이 m (기록)", kind: "number", min: 0, step: "any", advanced: true },
      { id: "soil", label: "토양조건 (기록)", kind: "select", advanced: true, options: [
        { value: "unspecified", label: "미지정" },
        { value: "dry", label: "건조" },
        { value: "moist", label: "보통" },
        { value: "wet", label: "습윤" },
      ] },
      { id: "demand", label: "수용률", kind: "number", min: 0, max: 1, step: "0.01", advanced: true },
      { id: "efficiency", label: "효율", kind: "number", min: 0, max: 1, step: "0.01", advanced: true },
      { id: "kTemp", label: "온도 보정계수 kθ (사용자 표)", kind: "number", min: 0, step: "any", advanced: true },
      { id: "kGroup", label: "집합 보정계수 (사용자 표)", kind: "number", min: 0, step: "any", advanced: true },
      { id: "kInstall", label: "포설 보정계수 (사용자 표)", kind: "number", min: 0, step: "any", advanced: true },
      { id: "selectedMm2", label: "선택 단면적 mm² (검토)", kind: "number", min: 0, step: "any", advanced: true },
      { id: "izTable", label: "표 허용전류 Iz A", kind: "number", min: 0, step: "any", advanced: true, hint: "KEC/IEC/제조사 표 값을 직접 넣으세요. 내장 표 없음." },
      { id: "iscKa", label: "단락전류 kA", kind: "number", min: 0, step: "any", advanced: true },
      { id: "tsc", label: "단락 지속시간 s", kind: "number", min: 0, step: "any", advanced: true },
      { id: "kAdiabatic", label: "단열계수 k (사용자 표)", kind: "number", min: 0, step: "any", advanced: true, hint: "비워 두면 열적 내량을 계산하지 않습니다. 임의 k를 넣지 마세요." },
    ],
  },
  "cable-parallel": {
    slug: "cable-parallel",
    layout: "complex",
    defaults: { current: "240", parallel: "2", area: "95", length: "60", lengthUnit: "m", material: "cu", lengthMismatchPct: "0" },
    fields: [
      { id: "current", label: "총 부하전류 A", kind: "number", required: true, min: 0, step: "any" },
      { id: "parallel", label: "병렬 수", kind: "number", required: true, min: 2, step: "1" },
      { id: "area", label: "1회선 단면적 mm²", kind: "number", required: true, min: 0, step: "any" },
      { id: "length", label: "길이", kind: "number", required: true, min: 0, step: "any", unitField: "lengthUnit", units: lengthUnits },
      { id: "material", label: "재질", kind: "select", options: cuAl },
      { id: "lengthMismatchPct", label: "길이 편차 추정 %", kind: "number", min: 0, step: "any", advanced: true },
    ],
  },
  "cable-ampacity": {
    slug: "cable-ampacity",
    layout: "complex",
    defaults: { designCurrent: "87", iz: "110", kTemp: "0.94", kGroup: "0.8", kOther: "1" },
    fields: [
      { id: "designCurrent", label: "설계전류 Ib A", kind: "number", required: true, min: 0, step: "any" },
      { id: "iz", label: "표 허용전류 Iz A", kind: "number", required: true, min: 0, step: "any", hint: "KEC/IEC/제조사 표를 직접 확인한 값" },
      { id: "kTemp", label: "온도 보정", kind: "number", required: true, min: 0, step: "any" },
      { id: "kGroup", label: "집합 보정", kind: "number", required: true, min: 0, step: "any" },
      { id: "kOther", label: "기타 보정", kind: "number", min: 0, step: "any" },
    ],
  },
  busbar: {
    slug: "busbar",
    layout: "complex",
    defaults: { current: "800", material: "cu", width: "80", thickness: "10", bars: "2", jAllow: "1.6", isc: "25", tsc: "1" },
    fields: [
      { id: "current", label: "전류 A", kind: "number", required: true, min: 0, step: "any" },
      { id: "material", label: "재질 (기록)", kind: "select", options: cuAl },
      { id: "width", label: "폭 mm", kind: "number", required: true, min: 0, step: "any" },
      { id: "thickness", label: "두께 mm", kind: "number", required: true, min: 0, step: "any" },
      { id: "bars", label: "병렬 매수", kind: "number", min: 1, step: "1" },
      { id: "jAllow", label: "사용자 허용 전류밀도 A/mm² (경험값)", kind: "number", min: 0, step: "any", hint: "표준 허용전류표가 아닙니다." },
      { id: "isc", label: "단락전류 kA (선택)", kind: "number", min: 0, step: "any" },
      { id: "tsc", label: "단락 지속 s", kind: "number", min: 0, step: "any" },
    ],
  },
  "transformer-sizing": {
    slug: "transformer-sizing",
    layout: "complex",
    defaults: { demandKw: "720", pf: "0.9", designMargin: "0.1", futureMargin: "0.15", distLoss: "0.03", vPrimary: "22900", vPrimaryUnit: "V", vSecondary: "380", vSecondaryUnit: "V", zPct: "6", cFactor: "1.05", mode: "basic" },
    fields: [
      { id: "mode", label: "계산 모드", kind: "select", options: [{ value: "basic", label: "기본 계산" }, { value: "detailed", label: "상세 계산" }] },
      { id: "demandKw", label: "최대수요전력 kW", kind: "number", required: true, min: 0, step: "any" },
      { id: "pf", label: "역률", kind: "number", min: 0, max: 1, step: "0.01" },
      { id: "designMargin", label: "설계 여유 (소수)", kind: "number", min: 0, step: "any", hint: "10%면 0.1", advanced: true },
      { id: "futureMargin", label: "향후 증설 여유 (소수)", kind: "number", min: 0, step: "any", advanced: true },
      { id: "distLoss", label: "예상 배전 손실 (소수)", kind: "number", min: 0, step: "any", advanced: true },
      { id: "vPrimary", label: "1차 전압", kind: "number", min: 0, step: "any", unitField: "vPrimaryUnit", units: voltageUnits, advanced: true },
      { id: "vSecondary", label: "2차 전압", kind: "number", min: 0, step: "any", unitField: "vSecondaryUnit", units: voltageUnits, advanced: true },
      { id: "zPct", label: "명판 %Z (단락 근사용)", kind: "number", min: 0, step: "any", advanced: true },
      { id: "cFactor", label: "전압계수 c", kind: "number", min: 0, step: "any", advanced: true, hint: "IEC 60909 표의 c는 전압 등급에 따라 다릅니다." },
    ],
  },
  "transformer-current": {
    slug: "transformer-current",
    layout: "complex",
    defaults: { ratedKva: "1000", vPrimary: "22900", vPrimaryUnit: "V", vSecondary: "380", vSecondaryUnit: "V" },
    fields: [
      { id: "ratedKva", label: "정격 kVA", kind: "number", required: true, min: 0, step: "any" },
      { id: "vPrimary", label: "1차 전압", kind: "number", required: true, min: 0, step: "any", unitField: "vPrimaryUnit", units: voltageUnits },
      { id: "vSecondary", label: "2차 전압", kind: "number", required: true, min: 0, step: "any", unitField: "vSecondaryUnit", units: voltageUnits },
    ],
  },
  "transformer-parallel": {
    slug: "transformer-parallel",
    layout: "complex",
    defaults: { s1: "1000", z1: "6", s2: "1000", z2: "6.5", loadKva: "1500" },
    fields: [
      { id: "s1", label: "TR1 용량 kVA", kind: "number", required: true, min: 0, step: "any" },
      { id: "z1", label: "TR1 %Z", kind: "number", required: true, min: 0, step: "any" },
      { id: "s2", label: "TR2 용량 kVA", kind: "number", required: true, min: 0, step: "any" },
      { id: "z2", label: "TR2 %Z", kind: "number", required: true, min: 0, step: "any" },
      { id: "loadKva", label: "공통 부하 kVA", kind: "number", required: true, min: 0, step: "any" },
    ],
  },
  "transformer-loss": {
    slug: "transformer-loss",
    layout: "complex",
    defaults: { ratedKva: "1000", noLoadKw: "1.2", loadLossKw: "10.5", loadKva: "800", pf: "0.9" },
    fields: [
      { id: "ratedKva", label: "정격 kVA", kind: "number", required: true, min: 0, step: "any" },
      { id: "noLoadKw", label: "무부하손 kW (명판)", kind: "number", required: true, min: 0, step: "any" },
      { id: "loadLossKw", label: "전부하 동손 kW (명판)", kind: "number", required: true, min: 0, step: "any" },
      { id: "loadKva", label: "실제 부하 kVA", kind: "number", required: true, min: 0, step: "any" },
      { id: "pf", label: "부하 역률", kind: "number", min: 0, max: 1, step: "0.01" },
    ],
  },
  "short-circuit": {
    slug: "short-circuit",
    layout: "complex",
    defaults: {
      voltage: "380",
      voltageUnit: "V",
      cFactor: "1.05",
      includeTr: "yes",
      trKva: "1000",
      trZpct: "6",
      trXr: "8",
      includeSource: "no",
      sourceMode: "sk",
      sourceMva: "250",
      sourceXr: "10",
      sourceR: "0.01",
      sourceX: "0.08",
      includeCable: "yes",
      cableM: "40",
      cableR: "0.193",
      cableX: "0.075",
      includeGen: "no",
      genKva: "500",
      genXd: "0.18",
      genXr: "12",
      includeMotor: "no",
      motorKva: "200",
      motorXd: "0.2",
    },
    fields: [
      { id: "voltage", label: "사고점 공칭 선간전압", kind: "number", required: true, min: 0, step: "any", unitField: "voltageUnit", units: voltageUnits },
      { id: "cFactor", label: "전압계수 c", kind: "number", min: 0, step: "any", hint: "IEC 60909 표 값은 전압 등급별로 다릅니다. 확인 후 입력." },
      { id: "includeTr", label: "변압기", kind: "select", options: [{ value: "yes", label: "포함" }, { value: "no", label: "제외" }] },
      { id: "trKva", label: "변압기 kVA", kind: "number", min: 0, step: "any", visibleWhen: { field: "includeTr", values: ["yes"] } },
      { id: "trZpct", label: "명판 %Z", kind: "number", min: 0, step: "any", visibleWhen: { field: "includeTr", values: ["yes"] } },
      { id: "trXr", label: "변압기 X/R", kind: "number", min: 0, step: "any", visibleWhen: { field: "includeTr", values: ["yes"] } },
      { id: "includeSource", label: "계통 전원", kind: "select", options: [{ value: "no", label: "무한모선 근사(변압기만)" }, { value: "yes", label: "임피던스 입력" }] },
      { id: "sourceMode", label: "계통 입력", kind: "select", options: [{ value: "sk", label: "단락용량 MVA" }, { value: "zx", label: "R, X Ω" }], visibleWhen: { field: "includeSource", values: ["yes"] } },
      { id: "sourceMva", label: "계통 단락용량 MVA", kind: "number", min: 0, step: "any", visibleWhen: { field: "sourceMode", values: ["sk"] } },
      { id: "sourceXr", label: "계통 X/R", kind: "number", min: 0, step: "any", visibleWhen: { field: "sourceMode", values: ["sk"] } },
      { id: "sourceR", label: "계통 R Ω", kind: "number", min: 0, step: "any", visibleWhen: { field: "sourceMode", values: ["zx"] } },
      { id: "sourceX", label: "계통 X Ω", kind: "number", min: 0, step: "any", visibleWhen: { field: "sourceMode", values: ["zx"] } },
      { id: "includeCable", label: "케이블", kind: "select", options: [{ value: "yes", label: "포함" }, { value: "no", label: "제외" }] },
      { id: "cableM", label: "케이블 길이 m", kind: "number", min: 0, step: "any", visibleWhen: { field: "includeCable", values: ["yes"] } },
      { id: "cableR", label: "케이블 R Ω/km", kind: "number", min: 0, step: "any", visibleWhen: { field: "includeCable", values: ["yes"] } },
      { id: "cableX", label: "케이블 X Ω/km", kind: "number", min: 0, step: "any", visibleWhen: { field: "includeCable", values: ["yes"] } },
      { id: "includeGen", label: "발전기 기여", kind: "select", options: [{ value: "no", label: "없음" }, { value: "yes", label: "포함" }] },
      { id: "genKva", label: "발전기 kVA", kind: "number", min: 0, step: "any", visibleWhen: { field: "includeGen", values: ["yes"] } },
      { id: "genXd", label: "x″d pu", kind: "number", min: 0, step: "any", visibleWhen: { field: "includeGen", values: ["yes"] } },
      { id: "includeMotor", label: "모터 기여분", kind: "select", options: [{ value: "no", label: "없음" }, { value: "yes", label: "포함" }] },
      { id: "motorKva", label: "운전 모터 합성 kVA", kind: "number", min: 0, step: "any", visibleWhen: { field: "includeMotor", values: ["yes"] } },
      { id: "motorXd", label: "모터 x″ pu", kind: "number", min: 0, step: "any", visibleWhen: { field: "includeMotor", values: ["yes"] }, hint: "명판 값이 없으면 넣지 말고 기여를 끄세요." },
    ],
  },
  "ct-ratio": {
    slug: "ct-ratio",
    layout: "complex",
    defaults: { loadCurrent: "80", primary: "100", secondary: "5", purpose: "metering", burdenVa: "15", leadOhm: "0.1" },
    fields: [
      { id: "loadCurrent", label: "부하전류 A", kind: "number", required: true, min: 0, step: "any" },
      { id: "primary", label: "CT 1차 정격 A", kind: "number", required: true, min: 0, step: "any", hint: "100, 200, 400 등" },
      { id: "secondary", label: "CT 2차", kind: "select", options: [{ value: "5", label: "5 A" }, { value: "1", label: "1 A" }] },
      { id: "purpose", label: "용도", kind: "select", options: [{ value: "metering", label: "계측" }, { value: "protection", label: "보호" }] },
      { id: "burdenVa", label: "부담 VA (선택)", kind: "number", min: 0, step: "any" },
      { id: "leadOhm", label: "리드 저항 Ω (선택)", kind: "number", min: 0, step: "any", advanced: true },
    ],
  },
  "pt-ratio": {
    slug: "pt-ratio",
    layout: "complex",
    defaults: { vPrimary: "22900", vPrimaryUnit: "V", vSecondary: "110", vSecondaryUnit: "V" },
    fields: [
      { id: "vPrimary", label: "1차 전압", kind: "number", required: true, min: 0, step: "any", unitField: "vPrimaryUnit", units: voltageUnits },
      { id: "vSecondary", label: "2차 전압", kind: "number", required: true, min: 0, step: "any", unitField: "vSecondaryUnit", units: voltageUnits },
    ],
  },
  "vfd-sizing": {
    slug: "vfd-sizing",
    layout: "complex",
    defaults: { motorKw: "30", motorA: "60", voltage: "380", voltageUnit: "V", margin: "0.1", derate: "1", loadType: "variable" },
    fields: [
      { id: "motorKw", label: "모터 kW", kind: "number", required: true, min: 0, step: "any" },
      { id: "motorA", label: "모터 전류 A (있으면)", kind: "number", min: 0, step: "any" },
      { id: "voltage", label: "전압", kind: "number", required: true, min: 0, step: "any", unitField: "voltageUnit", units: voltageUnits },
      { id: "loadType", label: "부하 특성 (기록)", kind: "select", options: [{ value: "variable", label: "변동 토크" }, { value: "constant", label: "일정 토크" }] },
      { id: "margin", label: "여유율 (소수)", kind: "number", min: 0, step: "any" },
      { id: "derate", label: "사용자 감소계수", kind: "number", min: 0, step: "any", hint: "고온·고지 등은 제조사 표를 넣어 1 미만으로" },
    ],
  },
  "soft-starter": {
    slug: "soft-starter",
    layout: "complex",
    defaults: { flc: "60", startMult: "3.5", startSec: "8", startsPerHour: "4" },
    fields: [
      { id: "flc", label: "모터 FLC A", kind: "number", required: true, min: 0, step: "any" },
      { id: "startMult", label: "기동 전류 배수", kind: "number", required: true, min: 0, step: "any" },
      { id: "startSec", label: "기동시간 s", kind: "number", required: true, min: 0, step: "any" },
      { id: "startsPerHour", label: "시간당 기동 횟수", kind: "number", required: true, min: 0, step: "any" },
    ],
  },
  "protection-relay": {
    slug: "protection-relay",
    layout: "complex",
    defaults: { pickup: "100", faultCurrent: "800", tms: "0.15", curve: "SI" },
    fields: [
      { id: "pickup", label: "픽업 전류 Is A", kind: "number", required: true, min: 0, step: "any" },
      { id: "faultCurrent", label: "사고전류 I A", kind: "number", required: true, min: 0, step: "any" },
      { id: "tms", label: "TMS / Time Dial", kind: "number", required: true, min: 0, step: "any" },
      {
        id: "curve",
        label: "IEC 반한시 곡선",
        kind: "select",
        options: [
          { value: "SI", label: "Standard Inverse" },
          { value: "VI", label: "Very Inverse" },
          { value: "EI", label: "Extremely Inverse" },
          { value: "LTI", label: "Long Time Inverse" },
        ],
      },
    ],
  },
  lux: {
    slug: "lux",
    layout: "complex",
    defaults: { length: "12", width: "8", lux: "300", lumens: "3200", uf: "0.55", mf: "0.8" },
    fields: [
      { id: "length", label: "공간 길이 m", kind: "number", required: true, min: 0, step: "any" },
      { id: "width", label: "폭 m", kind: "number", required: true, min: 0, step: "any" },
      { id: "lux", label: "목표 조도 lx", kind: "number", required: true, min: 0, step: "any" },
      { id: "lumens", label: "등기구 광속 lm", kind: "number", required: true, min: 0, step: "any" },
      { id: "uf", label: "이용률 UF", kind: "number", min: 0, max: 1, step: "0.01" },
      { id: "mf", label: "유지율 MF", kind: "number", min: 0, max: 1, step: "0.01" },
    ],
  },
  "lighting-density": {
    slug: "lighting-density",
    layout: "complex",
    defaults: { watts: "960", area: "96", oldWatts: "2400", hours: "3000", price: "140" },
    fields: [
      { id: "watts", label: "조명 전력 W", kind: "number", required: true, min: 0, step: "any" },
      { id: "area", label: "면적 m²", kind: "number", required: true, min: 0, step: "any" },
      { id: "oldWatts", label: "기존 전력 W (비교)", kind: "number", min: 0, step: "any" },
      { id: "hours", label: "연간 점등 h", kind: "number", min: 0, step: "any" },
      { id: "price", label: "평균 단가 원/kWh", kind: "number", min: 0, step: "any" },
    ],
  },
  "solar-pv": {
    slug: "solar-pv",
    layout: "complex",
    defaults: { mode: "grid", dailyKwh: "24", psh: "3.8", panelW: "450", efficiency: "0.78", autonomyH: "24", dod: "0.5", vdc: "48" },
    fields: [
      { id: "mode", label: "구성", kind: "select", options: [{ value: "grid", label: "계통연계" }, { value: "offgrid", label: "독립형" }, { value: "hybrid", label: "하이브리드" }] },
      { id: "dailyKwh", label: "일일 사용전력 kWh", kind: "number", required: true, min: 0, step: "any" },
      { id: "psh", label: "Peak Sun Hours", kind: "number", required: true, min: 0, step: "any", hint: "지역·월별 일사. 임의 내장값 없음" },
      { id: "panelW", label: "패널 W", kind: "number", required: true, min: 0, step: "any" },
      { id: "efficiency", label: "시스템 효율", kind: "number", min: 0, max: 1, step: "0.01" },
      { id: "autonomyH", label: "배터리 목표 시간 h", kind: "number", min: 0, step: "any", visibleWhen: { field: "mode", values: ["offgrid", "hybrid"] } },
      { id: "dod", label: "DOD", kind: "number", min: 0, max: 1, step: "0.01", visibleWhen: { field: "mode", values: ["offgrid", "hybrid"] } },
      { id: "vdc", label: "DC 공칭전압 V", kind: "number", min: 0, step: "any", visibleWhen: { field: "mode", values: ["offgrid", "hybrid"] } },
    ],
  },
  "grounding-rod": {
    slug: "grounding-rod",
    layout: "complex",
    defaults: { rho: "100", length: "2.4", diameter: "0.014", rods: "2", spaceFactor: "1.2" },
    fields: [
      { id: "rho", label: "토양저항률 Ω·m", kind: "number", required: true, min: 0, step: "any" },
      { id: "length", label: "봉 길이 m", kind: "number", required: true, min: 0, step: "any" },
      { id: "diameter", label: "봉 직경 m", kind: "number", required: true, min: 0, step: "any", hint: "14 mm → 0.014 m" },
      { id: "rods", label: "병렬 봉 수", kind: "number", min: 1, step: "1" },
      { id: "spaceFactor", label: "병렬 보정계수 (사용자)", kind: "number", min: 0, step: "any", hint: "간격이 짧으면 1보다 크게. 표 내장 없음" },
    ],
  },
  "soil-resistivity": {
    slug: "soil-resistivity",
    layout: "complex",
    defaults: { spacing: "5", resistance: "3.2" },
    fields: [
      { id: "spacing", label: "전극 간격 a m", kind: "number", required: true, min: 0, step: "any" },
      { id: "resistance", label: "측정 저항 R Ω", kind: "number", required: true, min: 0, step: "any" },
    ],
  },
  "earth-conductor": {
    slug: "earth-conductor",
    layout: "complex",
    defaults: { faultA: "5000", time: "0.5", kFactor: "", peInstall: "cable", peMaterial: "cu", peProtect: "protected" },
    fields: [
      { id: "faultA", label: "지락·단락전류 A", kind: "number", required: true, min: 0, step: "any" },
      { id: "time", label: "차단시간 s", kind: "number", required: true, min: 0, step: "any", hint: "KEC 142.3.2 단열식은 차단시간 5초 이하에만 적용합니다. 5초를 넘으면 열적 결과를 표시하지 않습니다. 설치조건 최소는 그대로 표시합니다." },
      { id: "kFactor", label: "재질·온도 계수 k", kind: "number", min: 0, step: "any", hint: "k 값은 도체 재질, 절연재료 및 허용온도 조건 등에 따라 관련 기준에서 확인하여 입력하세요. 구리=143 같은 기본값을 넣지 않습니다. t ≤ 5 s일 때 필요합니다." },
      {
        id: "peInstall",
        label: "보호도체 설치 형태",
        kind: "select",
        options: [
          { value: "cable", label: "케이블의 일부" },
          { value: "same-enclosure", label: "선도체와 동일 외함에 설치" },
          { value: "separate", label: "별도 보호도체" },
        ],
        hint: "별도 보호도체일 때만 Cu 2.5/4·Al 16 mm² 설치조건 최소를 적용합니다.",
      },
      {
        id: "peMaterial",
        label: "도체 재질",
        kind: "select",
        options: [
          { value: "cu", label: "구리" },
          { value: "al", label: "알루미늄" },
        ],
        visibleWhen: { field: "peInstall", values: ["separate"] },
      },
      {
        id: "peProtect",
        label: "기계적 손상에 대한 보호",
        kind: "select",
        options: [
          { value: "protected", label: "보호됨" },
          { value: "unprotected", label: "보호되지 않음" },
        ],
        visibleWhen: { field: "peInstall", values: ["separate"] },
        hint: "전선관, 트렁킹 내부 등 기계적 손상으로부터 보호되는 설치가 이에 해당할 수 있습니다. 특정 현장의 설치상태를 Ampory가 판정하지 않습니다.",
      },
    ],
  },
  "spd-helper": {
    slug: "spd-helper",
    layout: "complex",
    defaults: { location: "origin", un: "380", uc: "440", inKa: "25" },
    fields: [
      { id: "location", label: "설치 위치", kind: "select", options: [{ value: "origin", label: "인입" }, { value: "sub", label: "분전반" }, { value: "equip", label: "기기 근접" }] },
      { id: "un", label: "공칭전압 Un V", kind: "number", min: 0, step: "any" },
      { id: "uc", label: "검토 Uc V", kind: "number", min: 0, step: "any" },
      { id: "inKa", label: "검토 In kA (선택)", kind: "number", min: 0, step: "any" },
    ],
  },
  "generator-sizing": {
    slug: "generator-sizing",
    layout: "complex",
    defaults: { mode: "basic", staticKw: "120", motorKw: "55", motorStartK: "3", upsKw: "40", nonlinKw: "15", pf: "0.8", demand: "1", diversity: "0.85", margin: "0.15", ratedKw: "", largestMotorKw: "", startMethod: "dol" },
    fields: [
      { id: "mode", label: "계산 모드", kind: "select", options: [{ value: "basic", label: "기본 계산" }, { value: "detailed", label: "상세 계산" }] },
      { id: "staticKw", label: "일반부하 kW", kind: "number", min: 0, step: "any" },
      { id: "motorKw", label: "모터 축출력 합 kW", kind: "number", min: 0, step: "any" },
      { id: "upsKw", label: "UPS kW", kind: "number", min: 0, step: "any" },
      { id: "pf", label: "역률", kind: "number", min: 0, max: 1, step: "0.01" },
      { id: "nonlinKw", label: "기타 비선형 kW", kind: "number", min: 0, step: "any", advanced: true },
      { id: "demand", label: "수용률", kind: "number", min: 0, max: 1, step: "0.01", advanced: true },
      { id: "diversity", label: "동시사용률", kind: "number", min: 0, max: 1, step: "0.01", advanced: true },
      { id: "largestMotorKw", label: "최대 모터 kW", kind: "number", min: 0, step: "any", advanced: true, hint: "비우면 모터 합을 기동 기준으로 씁니다." },
      { id: "startMethod", label: "모터 기동방식 (기록)", kind: "select", advanced: true, options: [
        { value: "dol", label: "DOL" },
        { value: "yd", label: "Y-Δ" },
        { value: "soft", label: "소프트스타터" },
        { value: "vfd", label: "VFD" },
      ], hint: "배수는 자동으로 바꾸지 않습니다." },
      { id: "motorStartK", label: "기동전류 배수", kind: "number", min: 0, step: "any", advanced: true, hint: "제조사 기동 kVA가 있으면 그 경로를 쓰세요." },
      { id: "margin", label: "설계여유율 (소수)", kind: "number", min: 0, step: "any", advanced: true },
      { id: "ratedKw", label: "보유 발전기 kW (부하율 비교)", kind: "number", min: 0, step: "any", advanced: true },
    ],
  },
  "generator-fuel": {
    slug: "generator-fuel",
    layout: "complex",
    defaults: { mode: "estimate", loadKw: "320", hours: "8", litersPerKwh: "0.28", lPerHour: "90" },
    fields: [
      { id: "mode", label: "모드", kind: "select", options: [{ value: "estimate", label: "일반 추정 (L/kWh)" }, { value: "datasheet", label: "제조사 L/h" }] },
      { id: "loadKw", label: "부하 kW", kind: "number", required: true, min: 0, step: "any" },
      { id: "hours", label: "운전시간 h", kind: "number", required: true, min: 0, step: "any" },
      { id: "litersPerKwh", label: "추정 L/kWh", kind: "number", min: 0, step: "any", visibleWhen: { field: "mode", values: ["estimate"] }, hint: "기종마다 다름. 임의 표준값이 아님" },
      { id: "lPerHour", label: "제조사 연료소비 L/h", kind: "number", min: 0, step: "any", visibleWhen: { field: "mode", values: ["datasheet"] } },
    ],
  },
  "generator-start-vd": {
    slug: "generator-start-vd",
    layout: "complex",
    defaults: { genKva: "500", xd: "0.2", motorKva: "180" },
    fields: [
      { id: "genKva", label: "발전기 kVA", kind: "number", required: true, min: 0, step: "any" },
      { id: "xd", label: "사용자 pu 리액턴스", kind: "number", required: true, min: 0, step: "any", hint: "명판 x'd 또는 제조사 값" },
      { id: "motorKva", label: "기동 피상전력 kVA", kind: "number", required: true, min: 0, step: "any" },
    ],
  },
  "battery-capacity": {
    slug: "battery-capacity",
    layout: "complex",
    defaults: { loadW: "5000", dcV: "384", hours: "0.25", etaInv: "0.92", etaBatt: "0.9", aging: "0.8", dod: "0.8", cellV: "12", moduleAh: "100" },
    fields: [
      { id: "loadW", label: "부하 W", kind: "number", required: true, min: 0, step: "any" },
      { id: "dcV", label: "DC 전압 V", kind: "number", required: true, min: 0, step: "any" },
      { id: "hours", label: "백업시간 h", kind: "number", required: true, min: 0, step: "any", hint: "15분이면 0.25. 에너지 수지이며 방전곡선이 아님" },
      { id: "etaInv", label: "인버터 효율", kind: "number", min: 0, max: 1, step: "0.01", advanced: true },
      { id: "etaBatt", label: "배터리 효율", kind: "number", min: 0, max: 1, step: "0.01", advanced: true },
      { id: "aging", label: "노화 보정계수", kind: "number", min: 0, max: 1, step: "0.01", advanced: true },
      { id: "dod", label: "DOD", kind: "number", min: 0, max: 1, step: "0.01", advanced: true },
      { id: "cellV", label: "셀(모듈) 전압 V", kind: "number", min: 0, step: "any", advanced: true },
      { id: "moduleAh", label: "모듈 Ah (병렬 참고)", kind: "number", min: 0, step: "any", advanced: true },
    ],
  },
  "equipment-load": {
    slug: "equipment-load",
    layout: "complex",
    defaults: { ratedKw: "75", avgKw: "42", runHours: "420", periodHours: "730" },
    fields: [
      { id: "ratedKw", label: "정격 kW", kind: "number", required: true, min: 0, step: "any" },
      { id: "avgKw", label: "평균 전력 kW", kind: "number", required: true, min: 0, step: "any" },
      { id: "runHours", label: "기간 내 가동 h", kind: "number", min: 0, step: "any" },
      { id: "periodHours", label: "기간 h", kind: "number", min: 0, step: "any", hint: "월 ≈ 730 h" },
    ],
  },
  "energy-intensity": {
    slug: "energy-intensity",
    layout: "complex",
    defaults: { kwh: "125000", denominator: "10000", unitLabel: "m²" },
    fields: [
      { id: "kwh", label: "전력량 kWh", kind: "number", required: true, min: 0, step: "any" },
      { id: "denominator", label: "활동량", kind: "number", required: true, min: 0, step: "any" },
      { id: "unitLabel", label: "분모 단위 이름", kind: "select", options: [{ value: "m²", label: "m²" }, { value: "t", label: "생산 t" }, { value: "인", label: "인" }, { value: "대", label: "대수" }] },
    ],
  },
  "energy-cost": {
    slug: "energy-cost",
    layout: "complex",
    defaults: {
      mode: "bill",
      kwh: "15000",
      demandKw: "92",
      energyPrice: "",
      demandPrice: "",
      powerKw: "15",
      hoursPerDay: "10",
      daysPerMonth: "22",
      loadFactor: "1",
    },
    fields: [
      {
        id: "mode",
        label: "계산 종류",
        kind: "select",
        options: [
          { value: "bill", label: "검침 kWh 사용량 기반 비용 추정" },
          { value: "operating", label: "운전전력 × 시간 (kWh 수지)" },
        ],
      },
      { id: "kwh", label: "사용량 kWh", kind: "number", min: 0, step: "any", visibleWhen: { field: "mode", values: ["bill"] } },
      { id: "demandKw", label: "최대수요 kW", kind: "number", min: 0, step: "any", visibleWhen: { field: "mode", values: ["bill"] } },
      { id: "demandPrice", label: "기본요금 원/kW (사용자)", kind: "number", min: 0, step: "any", visibleWhen: { field: "mode", values: ["bill"] }, hint: "한전 요금표가 아닙니다. 비우면 0." },
      { id: "powerKw", label: "설비 입력전력 kW", kind: "number", required: true, min: 0, step: "any", visibleWhen: { field: "mode", values: ["operating"] } },
      { id: "hoursPerDay", label: "일 운전시간 h", kind: "number", required: true, min: 0, max: 24, step: "any", visibleWhen: { field: "mode", values: ["operating"] } },
      { id: "daysPerMonth", label: "월 운전일수", kind: "number", required: true, min: 0, max: 31, step: "any", visibleWhen: { field: "mode", values: ["operating"] } },
      { id: "loadFactor", label: "Load Factor", kind: "number", min: 0, max: 1, step: "0.01", visibleWhen: { field: "mode", values: ["operating"] }, hint: "평균/피크. 모르면 1." },
      { id: "energyPrice", label: "전력량 단가 원/kWh (사용자)", kind: "number", min: 0, step: "any", hint: "직접 입력. 기본 단가를 넣지 않습니다. 비우면 사용량만 계산합니다." },
    ],
  },
  "pm-interval": {
    slug: "pm-interval",
    layout: "complex",
    defaults: { runHours: "1850", intervalHours: "500" },
    fields: [
      { id: "runHours", label: "누적 운전 h", kind: "number", required: true, min: 0, step: "any" },
      { id: "intervalHours", label: "정비 주기 h", kind: "number", required: true, min: 0, step: "any" },
    ],
  },
  "yoy-energy": {
    slug: "yoy-energy",
    layout: "complex",
    defaults: { thisKwh: "14200", lastKwh: "12800", thisDemand: "90", lastDemand: "84" },
    fields: [
      { id: "thisKwh", label: "올해 동월 kWh", kind: "number", required: true, min: 0, step: "any" },
      { id: "lastKwh", label: "전년 동월 kWh", kind: "number", required: true, min: 0, step: "any" },
      { id: "thisDemand", label: "올해 최대수요 kW", kind: "number", min: 0, step: "any" },
      { id: "lastDemand", label: "전년 최대수요 kW", kind: "number", min: 0, step: "any" },
    ],
  },
  "field-compare": {
    slug: "field-compare",
    layout: "complex",
    defaults: { itemName: "유량", designValue: "100", measuredValue: "94", unit: "m3/h", toleranceMode: "percent", tolerancePct: "", toleranceAbs: "" },
    fields: [
      { id: "itemName", label: "항목명", kind: "text", placeholder: "예: 2차 전류, 급기 풍량" },
      { id: "designValue", label: "설계값 / 기준값", kind: "number", required: true, step: "any" },
      { id: "measuredValue", label: "실측값", kind: "number", required: true, step: "any" },
      { id: "unit", label: "단위", kind: "text", placeholder: "A, V, kW, m³/h 등" },
      {
        id: "toleranceMode",
        label: "허용편차 방식 (사용자)",
        kind: "select",
        options: [
          { value: "percent", label: "상대공차 ±%" },
          { value: "absolute", label: "절대공차 ± 단위값" },
        ],
        hint: "시방서 값을 넣으세요. Ampory가 공차를 정하지 않습니다.",
      },
      { id: "tolerancePct", label: "상대 허용편차 %", kind: "number", min: 0, step: "any", visibleWhen: { field: "toleranceMode", values: ["percent"] } },
      { id: "toleranceAbs", label: "절대 허용편차", kind: "number", min: 0, step: "any", visibleWhen: { field: "toleranceMode", values: ["absolute"] } },
    ],
  },
  "phase-unbalance": {
    slug: "phase-unbalance",
    layout: "complex",
    defaults: {
      unbalanceMethod: "avg-dev",
      vr: "380",
      vs: "383",
      vt: "377",
      ir: "",
      is: "",
      it: "",
      tolerancePct: "",
      vaMag: "220",
      vaAng: "",
      vbMag: "220",
      vbAng: "",
      vcMag: "220",
      vcAng: "",
    },
    fields: [
      {
        id: "unbalanceMethod",
        label: "계산 방식",
        kind: "select",
        options: [
          { value: "avg-dev", label: "평균편차 방식 (선간전압 RMS)" },
          { value: "vuf", label: "IEC 대칭분 VUF (위상 필요)" },
        ],
        hint: "선간 RMS 크기만으로는 IEC VUF를 계산하지 않습니다. 두 방식을 같은 한도로 취급하지 않습니다.",
      },
      { id: "vr", label: "Vab 선간전압 V", kind: "number", required: true, min: 0, step: "any", visibleWhen: { field: "unbalanceMethod", values: ["avg-dev"] } },
      { id: "vs", label: "Vbc 선간전압 V", kind: "number", required: true, min: 0, step: "any", visibleWhen: { field: "unbalanceMethod", values: ["avg-dev"] } },
      { id: "vt", label: "Vca 선간전압 V", kind: "number", required: true, min: 0, step: "any", visibleWhen: { field: "unbalanceMethod", values: ["avg-dev"] } },
      { id: "ir", label: "R 상전류 A", kind: "number", min: 0, step: "any", visibleWhen: { field: "unbalanceMethod", values: ["avg-dev"] } },
      { id: "is", label: "S 상전류 A", kind: "number", min: 0, step: "any", visibleWhen: { field: "unbalanceMethod", values: ["avg-dev"] } },
      { id: "it", label: "T 상전류 A", kind: "number", min: 0, step: "any", visibleWhen: { field: "unbalanceMethod", values: ["avg-dev"] } },
      { id: "tolerancePct", label: "참고 허용 % (사용자)", kind: "number", min: 0, step: "any", visibleWhen: { field: "unbalanceMethod", values: ["avg-dev"] }, hint: "비우면 한도와 비교하지 않습니다. 합격 판정이 아닙니다." },
      { id: "vaMag", label: "Va 크기 V", kind: "number", required: true, min: 0, step: "any", visibleWhen: { field: "unbalanceMethod", values: ["vuf"] } },
      { id: "vaAng", label: "Va 위상 °", kind: "number", step: "any", visibleWhen: { field: "unbalanceMethod", values: ["vuf"] }, hint: "정확한 대칭분 VUF 계산에는 위상정보가 필요합니다. ±120°를 자동으로 넣지 않습니다." },
      { id: "vbMag", label: "Vb 크기 V", kind: "number", required: true, min: 0, step: "any", visibleWhen: { field: "unbalanceMethod", values: ["vuf"] } },
      { id: "vbAng", label: "Vb 위상 °", kind: "number", step: "any", visibleWhen: { field: "unbalanceMethod", values: ["vuf"] } },
      { id: "vcMag", label: "Vc 크기 V", kind: "number", required: true, min: 0, step: "any", visibleWhen: { field: "unbalanceMethod", values: ["vuf"] } },
      { id: "vcAng", label: "Vc 위상 °", kind: "number", step: "any", visibleWhen: { field: "unbalanceMethod", values: ["vuf"] } },
    ],
  },
  "generator-load-test": {
    slug: "generator-load-test",
    layout: "complex",
    defaults: { ratedKw: "500", ratedKva: "625", phase: "3", voltage: "380", current: "420", pf: "", frequency: "", hours: "1", meterStart: "", meterEnd: "", i25: "", i50: "", i75: "", i100: "" },
    fields: [
      { id: "ratedKw", label: "발전기 정격 kW", kind: "number", min: 0, step: "any", hint: "kW 부하율을 볼 때만 필요합니다." },
      { id: "ratedKva", label: "발전기 정격 kVA", kind: "number", required: true, min: 0, step: "any" },
      { id: "phase", label: "상", kind: "select", options: [{ value: "3", label: "3상" }, { value: "1", label: "단상" }] },
      { id: "voltage", label: "선간전압 V", kind: "number", required: true, min: 0, step: "any" },
      { id: "current", label: "선전류 A", kind: "number", required: true, min: 0, step: "any" },
      { id: "frequency", label: "주파수 Hz (기록)", kind: "number", min: 0, step: "any" },
      { id: "pf", label: "역률 (있으면 kW 계산)", kind: "number", min: 0, max: 1, step: "0.01", hint: "비우면 kVA까지만. 0.8을 자동으로 넣지 않습니다." },
      { id: "hours", label: "운전시간 h (기록)", kind: "number", min: 0, step: "any" },
      { id: "meterStart", label: "시험 시작 계량 kWh (선택)", kind: "number", min: 0, step: "any" },
      { id: "meterEnd", label: "시험 종료 계량 kWh (선택)", kind: "number", min: 0, step: "any" },
      { id: "i25", label: "예시 25% 점 전류 A", kind: "number", min: 0, step: "any", advanced: true, hint: "법정 필수 단계가 아닙니다." },
      { id: "i50", label: "예시 50% 점 전류 A", kind: "number", min: 0, step: "any", advanced: true },
      { id: "i75", label: "예시 75% 점 전류 A", kind: "number", min: 0, step: "any", advanced: true },
      { id: "i100", label: "예시 100% 점 전류 A", kind: "number", min: 0, step: "any", advanced: true },
    ],
  },
  "duty-cycle": {
    slug: "duty-cycle",
    layout: "complex",
    defaults: { periodHours: "24", onHours: "8", offHours: "16", starts: "12" },
    fields: [
      { id: "periodHours", label: "관찰기간 h", kind: "number", required: true, min: 0, step: "any" },
      { id: "onHours", label: "ON 시간 h", kind: "number", required: true, min: 0, step: "any" },
      { id: "offHours", label: "OFF 시간 h", kind: "number", min: 0, step: "any", hint: "비우면 관찰기간 − ON. IEC 60034 Duty Type이 아닙니다." },
      { id: "starts", label: "기동횟수", kind: "number", min: 0, step: "1" },
    ],
  },
  "sensor-calibration": {
    slug: "sensor-calibration",
    layout: "complex",
    defaults: { spanMin: "0", spanMax: "100", ind1: "0.2", ref1: "0", ind2: "25.4", ref2: "25", ind3: "50.1", ref3: "50", ind4: "74.6", ref4: "75", ind5: "99.8", ref5: "100" },
    fields: [
      { id: "spanMin", label: "측정 Range Min", kind: "number", required: true, step: "any" },
      { id: "spanMax", label: "측정 Range Max", kind: "number", required: true, step: "any" },
      { id: "ind1", label: "P1 센서 표시값", kind: "number", step: "any" },
      { id: "ref1", label: "P1 Reference", kind: "number", step: "any" },
      { id: "ind2", label: "P2 센서 표시값 (25% 등)", kind: "number", step: "any", advanced: true },
      { id: "ref2", label: "P2 Reference", kind: "number", step: "any", advanced: true },
      { id: "ind3", label: "P3 센서 표시값", kind: "number", step: "any", advanced: true },
      { id: "ref3", label: "P3 Reference", kind: "number", step: "any", advanced: true },
      { id: "ind4", label: "P4 센서 표시값", kind: "number", step: "any", advanced: true },
      { id: "ref4", label: "P4 Reference", kind: "number", step: "any", advanced: true },
      { id: "ind5", label: "P5 센서 표시값", kind: "number", step: "any", advanced: true },
      { id: "ref5", label: "P5 Reference", kind: "number", step: "any", advanced: true },
    ],
  },
  "retrofit-compare": {
    slug: "retrofit-compare",
    layout: "complex",
    defaults: { baselineKw: "18", proposedKw: "11", baselineHours: "4000", proposedHours: "4000", baselineRate: "", proposedRate: "", capitalCost: "" },
    fields: [
      { id: "baselineKw", label: "기존 소비전력 kW", kind: "number", required: true, min: 0, step: "any" },
      { id: "baselineHours", label: "기존 연간 운전 h", kind: "number", required: true, min: 0, step: "any" },
      { id: "baselineRate", label: "기존 에너지 단가 원/kWh (사용자)", kind: "number", min: 0, step: "any" },
      { id: "proposedKw", label: "개선 후 소비전력 kW", kind: "number", required: true, min: 0, step: "any" },
      { id: "proposedHours", label: "개선 후 연간 운전 h", kind: "number", min: 0, step: "any", hint: "비우면 기존과 같음" },
      { id: "proposedRate", label: "개선 후 단가 원/kWh (사용자)", kind: "number", min: 0, step: "any" },
      { id: "capitalCost", label: "투자비 원 (선택)", kind: "number", min: 0, step: "any", hint: "넣으면 Simple Payback만 계산. NPV/IRR 없음." },
    ],
  },
};
